### ISSUE TITLE
Update packages to support null-safety and Flutter 2

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [freedomlayer/built_union.dart#13]
Hello, 

When I try to upgrade the packages, I get this error:

> Because built_union_generator 0.1.3 depends on built_collection >=2.0.0 <5.0.0 and no versions of built_union_generator match >0.1.3 <0.2.0, built_union_generator ^0.1.3 requires built_collection >=2.0.0 <5.0.0.

Can we do upgrade built_collection, built_value and analyzer, please?

**Comment by realcr** [comment]
@AhmedNourJamalElDin : Hey, thanks for reporting this issue!
If you believe the upgrade should be seamless, it will be very helpful if you can provide a pull request, and I will be happy to merge it. If the upgrade is more involved, it might take me a while to do it myself.
If you want to try it out, please check https://github.com/freedomlayer/built_union.dart#hacking-guide to see how to compile this package locally. 
Thanks!

**Comment by AhmedNourJamalElDin** [comment]
Hello,
I'm sorry but it seems null-safety must be supported too.
So I'm not sure I can do it with code generation.

let me know if I'm wrong and it can be done without null-safety migration, please.

**Comment by AhmedNourJamalElDin** [comment]
Any update, please?

**Comment by realcr** [comment]
@AhmedNourJamalElDin Hi, unfortunately I will not have the time to reach fixing this issue in the following months, but I am willing to merge a solution if provided.

**Comment by AhmedNourJamalElDin** [comment]
Hello @realcr 

I have made a PR #14  and it is working in my project.

**Comment by realcr** [comment]
@AhmedNourJamalElDin : Thank you for your contribution, and sorry for the late response. I just merged the PR.

Another question: Would you like to take ownership of this github project? I am not working with dart a lot these days, and I would really like that someone who actually uses this project will maintain it. I will also be happy to provide you with ownership over the pub.dev entry.

**Comment by AhmedNourJamalElDin** [comment]
Hello, thanks
I may accept this in the futur
