### ISSUE TITLE
Deserializing Using Attribute

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [freedomlayer/built_union.dart#9]
Hi,

Is it possible to deserialize an object using attribte?

Suppose I have classes:
```
class Type1 {
       string name;
       string value;
       string type;
       BuiltList<Type1> types1;
}

class Type2 {
       string name;
       string value;
       string type;
       BuiltList<Type2> types2;
}
```
and I need to deserialize based on the attribute called "type". if `type == "type1"`, the deserialized object must be of type `Type1`, if `type == "type2"`, the deserialized object must be of type `Type2`.

Thanks

**Comment by realcr** [comment]
Hey, this is what I would recommend to do:

```dart
@BuiltUnion()
class MyInner extends _$MyInner {
  static Serializer<MyInner> get serializer => _$myInnerSerializer;

  MyInner.type1(BuiltList<bool> myBool) : super.type1(myBool);
  MyInner.type2(BuiltList<int> myInt) : super.type2(myInt);
}

abstract class MyClass implements Built<MyClass, MyClassBuilder> {
  static Serializer<MyClass> get serializer => _$myClassSerializer;

  String get string;
  String get value;
  MyInner get inner;

  MyClass._();
  factory MyClass([void Function(MyClassBuilder) updates]) = _$MyClass;
}
```

You can also do something slightly different, like having the union as the external container.

EDIT: If you have no choice and the structures you described is that you get from the other endpoint as JSON, then I have no useful idea for you `¯\_(ツ)_/¯`

**Comment by AhmedNourJamalElDin** [comment]
As I see `inner` won't be the key name in your example but type1 or type2.

Thanks a lot
